version: "3.8"
services:

  juice:
    image: bkimminich/juice-shop:latest
    container_name: pyscan_juice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - pyscan_net

  nginx:
    image: nginx:stable
    container_name: pyscan_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - pyscan_net

  mysql:
    image: mysql:8.0
    container_name: pyscan_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pyscan_net

networks:
  pyscan_net:
    driver: bridge
